//
//  AchievementWireframe.swift
//  StashCoach
//
//  Created by Chanick Park on 3/19/20.
//  Copyright (c) 2020 Chanick Park. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AchievementWireframe: BaseWireframe {

    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "Achievement", bundle: nil)

    // MARK: - setup

    init() {
        // Create presenter with view and interactor
        let moduleViewController = storyboard.instantiateViewController(ofType: AchievementViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = AchievementInteractor()
        let presenter = AchievementPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

    private func openDetailView(with achievement: Achievement) {
        // Open detail view
        //navigationController?.pushWireframe(AchievementDetailWireframe(achievement))
        showAlert(with: "Warning", message: "This feature is unavailable now.")
    }
}

// MARK: - AchievementWireframeInterface

extension AchievementWireframe: AchievementWireframeInterface {
    func navigate(to option: AchievementNavigationOption) {
        switch option {
        case .details(let achievement):
            openDetailView(with: achievement)
        }
    }
    
}
