//
//  AchievementInterfaces.swift
//  StashCoach
//
//  Created by OGiP on 3/19/20.
//  Copyright (c) 2020 Chanick Park. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum AchievementNavigationOption {
    case details(Achievement)
}

protocol AchievementWireframeInterface: WireframeInterface {
    func navigate(to option: AchievementNavigationOption)
}

protocol AchievementViewInterface: ViewInterface {
    func updateData(_ title: String)
}

protocol AchievementPresenterInterface: PresenterInterface {
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> Achievement?
    func didSelectItem(at indexPath: IndexPath)
}

protocol AchievementInteractorInterface: InteractorInterface {
    func retrieveAchievement(_ complete: @escaping AchievementListCompletionBlock)
}
