//
//  AchievementInterfaces.swift
//  StashCoach
//
//  Created by Chanick Park on 3/19/20.
//  Copyright (c) 2020 Chanick Park. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum AchievementNavigationOption {
    // move to detail view when selected achievement cell
    case details(Achievement)
}

protocol AchievementWireframeInterface: WireframeInterface {
    // Route to other view
    func navigate(to option: AchievementNavigationOption)
}

protocol AchievementViewInterface: ViewInterface {
    // update view
    func updateData(_ title: String)
}

protocol AchievementPresenterInterface: PresenterInterface {
    // Access to Achievements
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> Achievement?
    func didSelectItem(at indexPath: IndexPath)
}

protocol AchievementInteractorInterface: InteractorInterface {
    // Communicate with network module
    func retrieveAchievement(_ complete: @escaping AchievementListCompletionBlock)
}
